### PR TITLE
Zopfli zlib (& testing gzip) for HTTP Compression Negotiation

### PR DESCRIPTION
**Pull request by snuggs**
## Summary
Haven't found a sane gzip cli in node and don't really feel need a programing environment for this. Just a good command line script with decent args that I don't have to manually build and install. Zopfli covers both. Also determining using [`gzip`](https://www.gnu.org/software/gzip/manual/gzip.html) (current *manually* installed library) vs [`zopfli`](https://www.npmjs.com/package/node-zopfli)  libraries for GZIP compression (also testing ZLIB compression with Zopfli).

## Reason
0. gzip node library doesn't have a good command line. Forces authoring JS 💩 
1. Personal gain
2. Being asked for documentation so at minimum `README.md` will be super valuable for links.

Satisfies [Content Negotiation](https://en.wikipedia.org/wiki/Content_negotiation) for `br`, `gzip`, `deflate` [`Accept-Encoding`]() advertisements for [`Content-Encoding tokens`](https://en.wikipedia.org/wiki/HTTP_compression#Content-Encoding_tokens)  respectively for graceful degradation. 

https://en.wikipedia.org/wiki/HTTP_compression

## Background Dependencies
- Koa Static _(used for `Content-Encoding` negotiation)_ - https://github.com/koajs/static

## Result
0. No need for *manual* installation of gzip make/installation anymore.
1. 💰  *7% savings* in `DEFLATE`d compression libraries. 💸
2. Stopped diff of `gzip` versions on every run. (Now is idempotent).
3. Better understanding of _"Content Encoding Negotiation"_
4. The browser warz back in the bad old dayz were shitty for everyone. One word... GREED!

### CODE REVIEW

**Comment by brandondees** [comment]
the diff implies that you have zopfli and brotli confused. i don't think you'd want to mix them together. zopfli is gzip but trading compress time for size savings. brotli is an entirely different, incompatible compression and has to be treated separately.

**Comment by snuggs** [comment]
@brandondees testing gzip differences not brotli. disabling brotli while testing. Will have both gzip and zopfli versions in for a bit while testing server payloads.

Hope this clears things up.

**Comment by snuggs** [comment]
Jus testing.

gzip, zlib, deflate _(respectfully)
capture d ecran 2017-07-09 a 10 17 19

**Comment by snuggs** [comment]
- `.br` - brotli
- *`.gz` - gzip _(via gzip library)_*
- *`.gz2` - gzip _(via zopfli library)_*
- `.zo` - zlib _(via zopfli)_

## Conclusion
Switching over to using `zopfli` 🏆 for `gzip` compression.

capture d ecran 2017-07-09 a 11 45 28

**Comment by snuggs** [comment]
@tmornini  just a heads up! Says you recently updated here.

capture d ecran 2017-07-09 a 14 24 21

**Comment by brandondees** [comment]
thanks for the clarification, all makes sense now.

**Pull request merged**
