### PR TITLE
🎉 🎉  #100 🎉 🎉  Element.select `body ${a}` and  Element.selectAll `body ${b}` String Interpolation

### LINKED ISSUE #99: `Element` Helpers Blow Up on String Interpolation
## Affected

- [ ] - `this.select (selector)` - Syntactic sugar around `this.querySelector ()`
- [ ] - `this.selectAll (selector)` - Syntactic sugar around `this.querySelectorAll ()`

## Repro

capture d ecran 2017-07-09 a 18 36 48

## Example

```html
<foo-bar>
  <p>Let's select this
    <img alt='' src=#>
  </p>
</foo-bar>

<script>

Element `foo-bar`

(class extends HTMLElement {

  onconnect () {
    const child = 'img'

    this.select `p ${child}`💥💥💥💥💥
})

</script>
```

## Reason

I believe it's due to us just finding out your average function can typically be called with backticks. 

```
window.alert `This actually works right now`
```

However falls apart on itself when the string parameter has to actually be interpolated. There is a routine that [Tagged Template Literals]() run through splitting the string into respective tokens.

## Reference Links

  - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals_and_escape_sequences

### PR DESCRIPTION
**Pull request by snuggs**
🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉 
🎉 🎉 🎉 🎉  🎉 🎉  🎉 🎉 🎉 🎉  #100 W00T 🎉 🎉 🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉 🎉 🎉 🎉
 🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉 

### [ParentNode](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode)

### CODE REVIEW

**Comment by snuggs** [comment]
@brandondees @tmornini @RobertChristopher  this is a great first pass and works. However... Not very _"[Tsuッ](https://en.wikipedia.org/wiki/Tsu_(kana)) style"_ and can be refactored more if i know me.

Will try a couple patterns out.
capture d ecran 2017-07-10 a 06 05 17

**Comment by snuggs** [comment]
MUCH Better Tsuッ

capture d ecran 2017-07-10 a 07 21 43

**Comment by snuggs** [comment]
Much better performance as well. Taking about `100μ _(m or 0.1ms)_ 
capture d ecran 2017-07-10 a 07 35 54
capture d ecran 2017-07-10 a 07 30 55

to go through selection process.

**Comment by brandondees** [comment]
that wp link doesn't provide info on what the word actually means! i'm gonna leave this one open to come back to and read properly though.

**Comment by snuggs** [comment]
@brandondees "Glottal Stop" is the term. think "UH-OH" it's the hyphen. Think `function (args)` it's the space. The definition is literally a getting back to "nothing" before continuing otherwise will be a run-on and communication overload. Kinda like how the front end is these days. @robcole may have a better Japanese lesson than that but it's as simple as "Uh-Oh" https://en.wikipedia.org/wiki/Glottal_stop

**Comment by snuggs** [comment]
@tmornini 
capture d ecran 2017-07-10 a 23 58 12

**Comment by snuggs** [comment]
@brandondees @pachonk @tmornini this turned out better than expected. Converting to `Tsuツ` style dropped feature down from 1kB addition to core to 30bytes _(1270OCTETS ➡️  1300OCTETS)_

capture d ecran 2017-07-11 a 06 31 54

**Comment by snuggs** [comment]
@brandondees perfect example of "Glottal Stop" in english. `Mixin` is NOT the same as `Mix-In`.

With ES6 and with prononciation.
capture d ecran 2017-07-11 a 10 44 39

**Pull request merged**
