### PR TITLE
eliminate odd formatting in README

### PR DESCRIPTION
**Pull request by tmornini**

### CODE REVIEW

**Comment by tmornini** [comment]
P.S. If you've been searching for this for weeks, you're not getting enough sleep. 😄

**Comment by snuggs** [comment]
Or the README was just too verbose. Been working on that. Every time i touched it i was like "where's that pesky backtick. lol /cc @brandondees

**Comment by snuggs** [comment]
@tmornini oh i was talking about one on the main README. Just put two and two together that you did this on `dist`. Any ideas for root one? 🙏

**Comment by tmornini** [comment]
Haha, I *thought* I was editing the root one!

Who needs the sleep now, smartass? :-)

What is the problem on the root one? I just looked it over and it looks pretty good to me...

**Comment by tmornini** [comment]
@brandondees We already did. :-)

**Pull request merged**
