### PR TITLE
features/nav-view

### PR DESCRIPTION
**Pull request by RobertChristopher**
Implemented declarative micro-router that maps url fragments to templates.

### CODE REVIEW

**Comment by RobertChristopher** [comment]
@snuggs Any thoughts? I want to get this merged.

**Comment by snuggs** [comment]
@RobertChristopher was away for the past week. Back at it again. Have added some commits to the branch. Will push later today.

**Comment by RobertChristopher** [comment]
@snuggs Can you push up your local commits? I want to see where your head is at. Need to get this merged soon.

**Comment by snuggs** [comment]
Will do @RobertChristopher ! Please review https://github.com/devpunks/snuggsi/pull/54

**Comment by snuggs** [comment]
@RobertChristopher I FOUND IT! I forgot had this PR open. This is all we need for `<hav-router>` worked on this with @VicenteRD. #FACTS!

https://github.com/NYCrb/devpunks/pull/19

**Comment by snuggs** [comment]
@RobertChristopher rebased this branch. should be good to go now. I've done some interesting things with fragment identifier relative to the PR above. check out http://snuggsi.herokuapp.com and click nav links on the left for example. Seems like this feature should introduce a `view` attribute at minimum. Only CSS needed for that.

Also did not have to add the script files to the package.json `bundle` command. Can do that from within the component itself since the only thing bundled are the core snuggsi dependencies. (i.e. `GlobalEventHandlers`)

**Comment by snuggs** [comment]
@RobertChristopher @mrbernnz @brandondees not too shabby!

**Pull request merged**
